artifacts_root: artifacts
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: "" # optional remote source URL (leave empty for local)
  local_data_file: data/poultry_diseases
  unzip_dir: data/poultry_diseases
prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.keras
training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.keras
model_evaluation:
  root_dir: artifacts/model_evaluation
  report_file: artifacts/model_evaluation/evaluation_report.json

serving:
  root_dir: artifacts/serving
  saved_model_dir: artifacts/serving/saved_model